### ISSUE TITLE
"How To Use" example doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [ZJULearning/efanna#7]
kbriggs:~/Downloads/efanna-master> cd samples/
kbriggs:~/Downloads/efanna-master/samples> ./efanna_index_buildgraph sift_base.fvecs sift.graph 8 8 8 30 25 10 10   
open file error

**Comment by CongFu92** [comment]
You should check the path of the dataset. It seems that you didn't provide the correct path of SIFT1M.
I suggest you reading the README and making sure that you know what our code is used for and what it needs.

**Comment by keithbriggs** [comment]
The example which doesn't work was taken from README.   If you give an explicit quick-start example, then it should work exactly as given.


K


________________________________

**Comment by CongFu92** [comment]
Yeah, I know it's in README. What I'm trying to explain is that you don't know what our code is used for. The example cannot run on itself. You need to provide data for it. 
Clearly, the error happens because you didn't provide the data it needs. sift_base.fvecs is the data file it needs. And the program cannot find it because you didn't put it there. 
You need to download the benchmark dataset (SIFT1M) and put it in the correct place.

I suggest again that you need to read the README to figure out what the program is used for.

**Comment by keithbriggs** [comment]
The implication in README is that this file is provided with the distribution in the samples directory.   I now see that it comes from somewhere else.


A spelling error in README: "seperately" should be "separately".


K

________________________________

**Comment by CongFu92** [comment]
OK， thank you.
